config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :albums
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :artists
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_many :albums

  def self.create_update_artists
    artists = Artist.get_external_artists

    artists.each do |artist|
      Artist.find_or_create_by(
        external_id: artist[:id],
        name: artist[:name],
        twitter: artist[:twitter]
      )
    end
  end

  def self.get_external_artists
    url = 'https://www.moat.ai/api/task/'
    headers = { Basic: 'ZGV2ZWxvcGVyOlpHVjJaV3h2Y0dWeQ==' }

    response = RestClient::Request.execute(
      method: :get,
      url: url,
      headers: headers
    )
    body = JSON.parse(response.body).flatten
    body = body.is_a?(Array) ? body.map { |hash| hash.transform_keys(&:to_sym) } : body.deep_symbolize_keys
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :user_name, :full_name, :password, presence: true
  validates :user_name, uniqueness: true

  def authenticate(password:)
    return true if self.password == password

    raise ArgumentError, 'Password incorrect.'
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  before_action :set_album, only: %i[edit destroy update]
  before_action :current_user
  before_action :admin

  def index
    @albums = Album.includes(:artist).all.order(:name).page(params[:page]).per(5)
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = 'Album created successful!'
      redirect_to albums_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_album_path
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path, notice: 'Album succsses updated'
    else
      render :edit
    end
  end

  def destroy
    if @album.destroy
      redirect_to albums_path, notice: 'Album deleted!'
    else
      render :index
    end
  end

  private

  def album_params
    params.require(:album).permit(:artist_id, :name, :year)
  end

  def set_album
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :admin

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def user_present
    redirect_to root_url, notice: 'you are not logged in!' unless current_user.present?
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  before_action :current_user
  before_action :admin

  def index
    @artists = Artist.all.order(:name).page(params[:page]).per(10)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
    unless user.present?
      raise ArgumentError,
            'Sorry, we could not find an account with this username. Please check you are using the right username and try again.'
    end

    user.authenticate(password: params[:password])

    session[:user_id] = user.id
    redirect_to artists_path, notice: 'Logged in!'
  rescue ArgumentError => e
    flash.now[:errors] = e
    render 'new'
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      flash[:success] = 'User created successful!'
      redirect_to artists_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.permit(:full_name, :user_name, :password, :role)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    level = level.to_sym
    case level
    when :notice then 'alert alert-primary'
    when :success then 'alert alert-success'
    when :errors then 'alert alert-danger'
    end
  end
end

app/views/albums/_form.html.erb
<div class="panel-body">
  <%= form_for(album) do |f| %>
    <fieldset>
      <div class="form-group horizontal-padding">
      <label for="exampleInputEmail1">Artist</label><br/>
        
        <%= f.collection_select :artist_id, Artist.all, :id, :name,
          prompt: 'Select a artist', include_blank: false, class: 'form-control' %>
      </div>
      <div class="form-group horizontal-padding">
      <label for="exampleInputEmail1">Name</label><br/>
        <%= f.text_field :name %>
      </div>
      <div class="form-group horizontal-padding">
      <label for="exampleInputEmail1">Year</label><br/>
        <%= f.text_field :year %>
      </div>
      <div class="button horizontal-padding">
        <%= f.submit "Save", class:"btn btn-lg btn-success btn-block" %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/albums/edit.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title horizontal-padding">Edit Album</h3>
      </div>
      <%= render 'form', album: @album %>
  </div>
</div>

app/views/albums/index.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
<main>

 <section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Welcome to your Albums List <%= current_user.full_name %></h1>
    </div>
  </div>
</section>

<div class="table-responsive horizontal-padding">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
          <th style="width: 120px"> Album Year </th>
          <th> Album Name </th>
          <th> Artist </th>
          <th>
            <%= link_to "New", new_album_path, class: "btn btn-success", style: "width: 130px"  %>
          </th>
      </tr>
    </thead>
      <tbody>
        <% @albums.each do |album| %>
          <tr>
            <td><%= album.year %></td>
            <td><%= album.name %></td>
            <td><%= album.artist.name %></td>
            <td style="width: 100px">
            <div class=btn-group>
              <%= link_to "Edit", edit_album_path(album), class: "btn btn-primary" %>

              <% unless current_user.role == "user" %>
              <%= button_to "Delete", album_path(id: album.id), method: :delete, class: "btn btn-danger" %>
              <% end %>
            </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @albums%>
</div>

app/views/albums/new.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title horizontal-padding">Creating Album</h3>
      </div>
      <%= render 'form', album: @album %>
  </div>
</div>

app/views/artists/index.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
<main>

 <section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Welcome to your Artists List <%= current_user.full_name %></h1>
    </div>
  </div>
</section>

<div class="table-responsive horizontal-padding">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
          <th> Artist ID </th>
          <th> Artist Name </th>
          <th> Artist Twitter </th>
      </tr>
    </thead>
      <tbody>
        <% @artists.each do |artist| %>
          <tr>
            <td><%= artist.id %></td>
            <td><%= artist.name %></td>
            <td><%= artist.twitter %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
  <%= paginate @artists%>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicAlbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar navbar-dark bg-dark shadow-sm horizontal-padding">
        <div>
        <%= link_to "Home", root_path, class: "btn btn-secondary" %>
        <% if current_user.present? %>
          <%= link_to "Music Album", albums_path, class: "btn btn-secondary" %>
          <%= link_to "Artists", artists_path, class: "btn btn-secondary" %>
        <% end %>
        </div>    
        <div class="button">
        <% if current_user.present? %>
            <%= link_to "Sign out", logout_path, method: :delete, class: "btn btn-secondary" %> 
        <% end %>    
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>
  <div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title horizontal-padding">Please sign up !</h3>
      </div>
      <div class="panel-body">
        <%= form_tag(@user, url: users_path(@user)) do %>
        <fieldset>
          <div class="form-group horizontal-padding">
          <label for="exampleInputEmail1">Full Name</label><br/>
            <%= text_field_tag :full_name %>
          </div>
          <div class="form-group horizontal-padding">
          <label for="exampleInputEmail1">User name</label><br/>
            <%= text_field_tag :user_name %>
          </div>
          <div class="form-group col-md-4 horizontal-padding">
          <label for="exampleInputEmail1">Role</label><br/>
             <%= select_tag :role, options_for_select([["Select One", ""], "admin", "user", ]), {:class => 'form-control'}  %>
          </div>
          <div class="form-group horizontal-padding">
          <label for="exampleInputEmail1">Password</label><br/>
            <%= password_field_tag :password %>
          </div>
          <div class="button horizontal-padding">
            <%= submit_tag "Sign up", class:"btn btn-lg btn-success btn-block" %>
          </div>
          </fieldset>
        <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Welcome Album Music Website !</h1>
        <br/>
        <h1 class="fw-light">Please sign in or sign up to continue</h1>
      </div>
    </div>
    <div class="row py-lg-1">
      <div class="col-lg-6 col-md-8 mx-auto">
        <%= link_to "Sign in", new_session_path, class: "btn btn-secondary" %>
      </div>
    </div>
      <div class="row py-lg-1">
        <div class="col-lg-6 col-md-8 mx-auto">
          <%= link_to "Sign up", new_user_path, class: "btn btn-secondary" %>
        </div>
      </div>
</section>